-- users

CREATE TABLE users (
    user_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    username varchar 200 NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    zip integer NOT NULL,
    hashed_password text NOT NULL
);

 --favorites
CREATE TABLE favorites (
    fav_id integer GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    user_id integer REFERENCES users(user_id),
    bus_id text UNIQUE,
    bus_name text,
    bus_image text,
    bus_rating float,
    bus_price integer,
    bus_address text,   --display address
    bus_phone text,    -- display phone

);
